### PR TITLE
Added RRDNS modified version of tcpdump-watch.sh as tcpdump-watch-rrdns.sh

### PR DESCRIPTION
**Pull request by jeztucker**
Very minor modifications as a secondary script to take account of multiple shares mounted from RRDNS provided servers.

### CODE REVIEW

**Comment by jeztucker** [comment]
Perhaps an uber script is more prudent, but as the tcpdump-watch.sh is referred to in official RH docs, I though it might be best not to alter the original.

**Comment by squizzi** [comment]
Hi Jez, 

Your changes to the `tcpdump-watch.sh` script look fine.  I wouldn't worry too much about the "old version" of `tcpdump-watch.sh` living on.  The old version will probably continue to live on downstream in some of Red Hat's documentation.  I'd rather the upstream tool grow in capability while still retaining its core functionality in a way that's familiar to the old version.

So, I think it'd be better to go with the "uber" script method.  Perhaps adding a `--rrdns` flag that forces the requirement of `nfs_server_export` and implement a proper `--help` to guide users to the RR DNS capabilities.

**Comment by jeztucker** [comment]
Hi Kyle,

  So if we improved the main tcpdump-watch.sh script with the usual getopt etc. plus the rrdns / other functionality several thoughts: 1) I would typically use python2.7 but perhaps bash is 'better' (hmm) as it's ubiquitous across multiple OS 2) should we go with the mountaddr in all cases?  If you know the IP of the server there is no need to perform a host lookup.  This removes any situation where the server IP is mounted but entries have not been made in a DNS.  3) should we kill this pull request as per your comments above and make a proper spec list?

**Comment by squizzi** [comment]
> 1) I would typically use python2.7 but perhaps bash is 'better' (hmm) as it's ubiquitous across multiple OS

I'm not against using python, I actually prefer it myself.  The only requirement I would have for python would be that we try to steer clear of using libraries that aren't shipped in enterprise distros, like RHEL.  We can't have people installing `python-pip` from EPEL.  

We can probably "archive" the old shell versions in their own branch and focus on making a python script that's a bit more robust.  

> 2) should we go with the mountaddr in all cases? If you know the IP of the server there is no need to perform a host lookup. This removes any situation where the server IP is mounted but entries have not been made in a DNS. 

There's circumstances where we ask users to utilize this script when they don't even have a NFS mount active, perhaps they're having an issue actually performing the mount.  This is why we can't rely on the mountaddr, as it may not always exist.

> 3) should we kill this pull request as per your comments above and make a proper spec list?

I will merge this request and it will be "archived" to it's own branch as part of the shell scripts collection so it can be used while we work towards a new python script. 

I've filed issue #3 to track work towards the python enhancement.

**Comment by squizzi** [comment]
@jeztucker Can you squash your changes and sign-off your commit and I'll merge it?

**Comment by jeztucker** [comment]
Hi.  I had to re-merge as master had diverged.  Commits have been signed off.

**Pull request merged**
